[package]
name = "node-rust-ffi"
version = "0.2.3"
authors = ["alfinsuryaS <benjaminstwo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"

[lib]
name = "embed"
crate-type = ["dylib"]

